### ISSUE TITLE
DeprecationWarnings inside log.

### ISSUE THREAD

**Issue by jkroepke** [eLco/setup-vault#1]
Using this action generates deprecations warnings

```
(node:1128) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by eLco** [comment]
Thank you for pointing this out. I do know about it :) Just didn’t have time to convert to new methods - https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/

**Comment by jkroepke** [comment]
I though bump dependencies is enough

**Comment by eLco** [comment]
Will check tomorrow, thank you!

**Comment by eLco** [comment]
Fixed in https://github.com/eLco/setup-vault/commit/694ab7d78e8014f1e0f25f3c69d80df15c40e3b1

Thank you @jkroepke
